name: Publish image to Docker Hub
on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          docker build ./Docker/ -t obstdev/wireguard-client:latest
      - name: publish
        run: |
          docker login -u obstdev -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push obstdev/wireguard-client:latest
