name: Publish image to Docker Hub
on:
  push:
    branches: [ "main" ]
    paths:
      - 'Docker/**'

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/wireguard-client
          tags: |
            type=raw,value={{date 'YYYYMMDD-HHmmss'}}

      - name: build
        run: |
          docker build ./Docker/ -t ${{ steps.meta.outputs.tags }}

      - name: publish
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push ${{ steps.meta.outputs.tags }}

