name: Publish image to Docker Hub
on:
  push:
    branches: [ "main" ]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: name/app
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}

      - name: build
        run: |
          docker build ./Docker/ -t obstdev/wireguard-client:${{ steps.meta.outputs.tags }}

      - name: publish
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push obstdev/wireguard-client:${{ steps.meta.outputs.tags }}

